### ISSUE TITLE
Request: Allow VMs without floating IPs

### ISSUE THREAD

**Issue by drwahl** [jenkinsci/openstack-cloud-plugin#128]
There are times when a user may want a VM allocated, but doesn't need a floating IP.  For example, some clouds allow VMs directly on the public network.  Also, it's possible a jenkins server might be on the same network as the VM that is being requested, thus, no floating IP is needed.  Please provide support for launching VMs without having to allocate/assign/use a floating IP.

**Comment by pjdarton** [comment]
If you use JNLP instead of SSH for the slave connection method then it's the VM's responsibility to connect to the Jenkins server, rather than the other way around, and no floating IP is required.
e.g. My OpenStack systems have a limited supply of routable IP addresses, so we use a non-routable private network (10.something) and NAT (to allow them to connect to the company network) for most VMs, and then those VMs connect to Jenkins via JNLP.

Note: To do this with version 2.17 of the openstack plugin, you'd have to configure your Jenkins server to permit anonymous users to connect a slave (if you manually create a dummy JNLP slave entry, look at the "how to launch the slave" instructions and see that it's telling you to specify a "-secret" argument then your security settings aren't permitting anonymous slave connections) *and* you'll also have to use a version of Jenkins prior to version 2.27.  https://github.com/jenkinsci/openstack-cloud-plugin/pull/135 is intended to resolve these issues.

If you need to use SSH then this would require further plugin enhancements to make the code find what non-floating IP address(es) had been assigned to the VM and use that.  I'm not sure how easy it'd be to extract that information from OpenStack, but I'm sure it'd be possible.
However, if you need a solution "now", use JNLP.

**Comment by olivergondza** [comment]
> If you need to use SSH then this would require further plugin enhancements to make the code find what non-floating IP address(es) had been assigned to the VM and use that. I'm not sure how easy it'd be to extract that information from OpenStack, but I'm sure it'd be possible.

The thing is there are deployments where floating IP is required to access openstack from Jenkins - hence the default. I dare to say the code is ready for machines to come up without floating IPs so fixed IPs will be used as fallback: https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java#L350-L369.

This whole task seems to boil down to adjust form configuration and openstack communication so the FIP is not requested. Unfortunately, I do not have an environment to test this.

**Comment by pjdarton** [comment]
If you can explain what you require to test this, maybe I can help.   I've got access to a couple of service endpoints (one v2 auth, one v3)...
I'm still learning OpenStack "as I go", so I'm not (currently) entirely clear on the difference between a "floating IP" and one you get purely from assigning a network to the VM (thus far, I've not used floating IPs, although I have found where they are on our "Horizon" OpenStack WebUI), but if if it won't take too long and you can tell me what to do then I could things out and let you know the results.

e.g. would I be right in thinking that a test scenario would be a Jenkins SSH-based slave which is *not* assigned to a network but which *is* assigned a floating IP?

**Comment by drwahl** [comment]
I was able to workaround this bug by using the jclouds plugin along with the "slave check-in" feature.  However, it is much more complicated to configure jclouds to talk to the openstack cluster than it was with this plugin.  I'm happy to continue to supply feedback for this issue, but given I have a working workaround, I'm also willing to let this one go.

**Comment by olivergondza** [comment]
> would I be right in thinking that a test scenario would be a Jenkins SSH-based slave which is not assigned to a network but which is assigned a floating IP?

IMO, we need it the other way around. In network but without FIP.

> If you can explain what you require to test this, maybe I can help. I've got access to a couple of service endpoints (one v2 auth, one v3)...

This should be testable/tested on functional test level. The request sent should not require it, the mocked server provisioned should not contain FIP and Jenkins should pick the fixed one.

**Comment by olivergondza** [comment]
Ok, I have gave this a try and it seems to work as expected as long as I can tell from my limited ability to reproduce. Configuration page offers "None specified" in FIP pool select option, when that is selected no FIP is requested nor assigned and Jenkins start to initiate connection using fixed address. That is where I am stuck as I fail to reach the fixed address on my instance in time (or ever).

How exactly does the problem manifests for you?

**Comment by minz1027** [comment]
@olivergondza I have no problem launching the instance. But it cannot be deleted since I do not have permission to even list the floating IPs. I will get 403 at this line here: https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java#L324

And the instance will never be deleted from openstack...
Can you just skip the floating IPs stuff during deletion if there is a 403 or user configure not to use floating IPs?

**Comment by olivergondza** [comment]
@minz1027, good point. Can you attach full exception thrown in such case? thanks

**Comment by minz1027** [comment]
@olivergondza 
```
Apr 12, 2017 6:43:47 PM jenkins.plugins.openstack.compute.SlaveOptionsDescriptor doFillFloatingIpPoolItems
SEVERE: Policy doesn't allow compute_extension:floating_ip_pools to be performed.
ClientResponseException{message=Policy doesn't allow compute_extension:floating_ip_pools to be performed., status=403, status-code=FORBIDDEN}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:47)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:67)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.getPoolNames(ComputeFloatingIPServiceImpl.java:40)
	at jenkins.plugins.openstack.compute.internal.Openstack.getSortedIpPools(Openstack.java:165)
	at jenkins.plugins.openstack.compute.SlaveOptionsDescriptor.doFillFloatingIpPoolItems(SlaveOptionsDescriptor.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by olivergondza** [comment]
@minz1027, @drwahl, can you give master branch a try?

**Comment by drwahl** [comment]
I'll give it a try soon(tm).
