### ISSUE TITLE
NullPointerException from UserDataVariableResolver

### ISSUE THREAD

**Issue by rohanpm** [jenkinsci/openstack-cloud-plugin#148]
On version 2.20 of the plugin, provision of slaves started to fail with:

```
java.lang.NullPointerException
	at jenkins.plugins.openstack.compute.UserDataVariableResolver$Entry.access$500(UserDataVariableResolver.java:101)
	at jenkins.plugins.openstack.compute.UserDataVariableResolver.resolve(UserDataVariableResolver.java:98)
	at jenkins.plugins.openstack.compute.UserDataVariableResolver.resolve(UserDataVariableResolver.java:40)
	at hudson.Util.replaceMacro(Util.java:174)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provision(JCloudsSlaveTemplate.java:272)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provision(JCloudsSlaveTemplate.java:212)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:179)
	at jenkins.plugins.openstack.compute.JCloudsCloud$NodeCallable.call(JCloudsCloud.java:347)
	at jenkins.plugins.openstack.compute.JCloudsCloud$NodeCallable.call(JCloudsCloud.java:333)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I downgraded the plugin to 2.17 and it fixed the problem.

I use the "user data" feature to deploy a shell script for provisioning.  It has some ${...} syntax which is expected to be parsed by the shell.  From a brief review of the code, I thought the problem may be that 59901b55154459f7697ffd9efe50f1085c40229a (introduced in 2.19) means that if ${foo} appears in the UserData, and "foo" is not one of the known variables being processed by Util.replaceMacro, then it will crash; while the previous behavior was instead to pass through the unresolved variable verbatim without macro replacement.

**Comment by olivergondza** [comment]
Thanks for reporting this.
