### ISSUE TITLE
OpenStackj4 Neutron Networks object incompatible

### ISSUE THREAD

**Issue by Chekov2k** [jenkinsci/openstack-cloud-plugin#189]
We are running an Kolla Pike 5.0.0 release OpenStack cluster and are getting a connection issue (see below). By the looks of it, the network object returned by the API does not seem compatible. We are using Jenkins version 2.60.3 and a plugin version of 2.29

```
Connection not validated, plugin might not operate correctly: Root name 'networks' does not match expected ('network') for type [simple type, class org.openstack4j.openstack.networking.domain.NeutronNetwork]
at [Source: {"networks":[{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"03e8c170-917f-43b2-a4e4-e4b875f9a683","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["6c656a61-b772-42b1-8add-4bc990811309"],"description":"","tags":[],"updated_at":"2018-02-05T11:03:13Z","qos_policy_id":null,"name":"dong","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T11:03:13Z","mtu":1450},{"updated_at":"2018-01-31T08:44:58Z","dns_domain":"","revision_number":9,"port_security_enabled":true,"id":"19576d0f-9e2f-43ce-ab2d-182f73998c5d","router:external":true,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"2b21740906894aaa908a8a443943aaf8","status":"ACTIVE","subnets":["8857b71d-52ae-4e0e-a72c-7ac1dcd78425"],"description":"","tags":[],"ipv6_address_scope":null,"is_default":false,"qos_policy_id":null,"name":"external","admin_state_up":true,"tenant_id":"2b21740906894aaa908a8a443943aaf8","created_at":"2018-01-18T11:19:44Z","mtu":1500},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"219b777e-76b5-4086-827f-67b8e6225d8a","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8f07dab4-0168-407a-8bb5-d2b02e7c7ff8"],"description":"","tags":[],"updated_at":"2018-01-31T10:16:11Z","qos_policy_id":null,"name":"test-fp","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-01-31T10:16:10Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"39aea290-5b63-4240-9c0f-cec5cd902d50","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8a464019-3fc4-450d-9e20-6b64c1f4a95d"],"description":"","tags":[],"updated_at":"2018-02-05T15:20:51Z","qos_policy_id":null,"name":"shift_on_stack","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T15:20:03Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"8025ff2d-19d6-4456-b765-d855a211b05d","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8d165d58-fa04-46c5-8919-6fbcbe8ed4db"],"description":"","tags":[],"updated_at":"2018-02-05T10:15:04Z","qos_policy_id":null,"name":"bam","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T10:15:03Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"dd477cb7-ae97-41da-a8f7-55b25062b83d","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["bd5be583-2d72-4fa9-8b01-802f66f72caa"],"description":"","tags":[],"updated_at":"2018-01-18T11:51:08Z","qos_policy_id":null,"name":"internal","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-01-18T11:51:07Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"e510a7fc-042b-4cde-8213-c493d3c83ed5","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["3c35c4da-47a1-44cd-9cd5-2f9abc1f484d"],"description":"","tags":[],"updated_at":"2018-02-05T10:22:47Z","qos_policy_id":null,"name":"joes-shift-on-stack","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T10:22:25Z","mtu":1450}]}; line: 1, column: 2]
com.fasterxml.jackson.databind.JsonMappingException: Root name 'networks' does not match expected ('network') for type [simple type, class org.openstack4j.openstack.networking.domain.NeutronNetwork]
 at [Source: {"networks":[{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"03e8c170-917f-43b2-a4e4-e4b875f9a683","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["6c656a61-b772-42b1-8add-4bc990811309"],"description":"","tags":[],"updated_at":"2018-02-05T11:03:13Z","qos_policy_id":null,"name":"dong","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T11:03:13Z","mtu":1450},{"updated_at":"2018-01-31T08:44:58Z","dns_domain":"","revision_number":9,"port_security_enabled":true,"id":"19576d0f-9e2f-43ce-ab2d-182f73998c5d","router:external":true,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"2b21740906894aaa908a8a443943aaf8","status":"ACTIVE","subnets":["8857b71d-52ae-4e0e-a72c-7ac1dcd78425"],"description":"","tags":[],"ipv6_address_scope":null,"is_default":false,"qos_policy_id":null,"name":"external","admin_state_up":true,"tenant_id":"2b21740906894aaa908a8a443943aaf8","created_at":"2018-01-18T11:19:44Z","mtu":1500},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"219b777e-76b5-4086-827f-67b8e6225d8a","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8f07dab4-0168-407a-8bb5-d2b02e7c7ff8"],"description":"","tags":[],"updated_at":"2018-01-31T10:16:11Z","qos_policy_id":null,"name":"test-fp","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-01-31T10:16:10Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"39aea290-5b63-4240-9c0f-cec5cd902d50","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8a464019-3fc4-450d-9e20-6b64c1f4a95d"],"description":"","tags":[],"updated_at":"2018-02-05T15:20:51Z","qos_policy_id":null,"name":"shift_on_stack","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T15:20:03Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"8025ff2d-19d6-4456-b765-d855a211b05d","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8d165d58-fa04-46c5-8919-6fbcbe8ed4db"],"description":"","tags":[],"updated_at":"2018-02-05T10:15:04Z","qos_policy_id":null,"name":"bam","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T10:15:03Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"dd477cb7-ae97-41da-a8f7-55b25062b83d","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["bd5be583-2d72-4fa9-8b01-802f66f72caa"],"description":"","tags":[],"updated_at":"2018-01-18T11:51:08Z","qos_policy_id":null,"name":"internal","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-01-18T11:51:07Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"e510a7fc-042b-4cde-8213-c493d3c83ed5","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["3c35c4da-47a1-44cd-9cd5-2f9abc1f484d"],"description":"","tags":[],"updated_at":"2018-02-05T10:22:47Z","qos_policy_id":null,"name":"joes-shift-on-stack","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T10:22:25Z","mtu":1450}]}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1648)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1572)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1200)
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.readEntity(HttpResponseImpl.java:122)
Caused: ClientResponseException{message=Root name 'networks' does not match expected ('network') for type [simple type, class org.openstack4j.openstack.networking.domain.NeutronNetwork]
 at [Source: {"networks":[{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"03e8c170-917f-43b2-a4e4-e4b875f9a683","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["6c656a61-b772-42b1-8add-4bc990811309"],"description":"","tags":[],"updated_at":"2018-02-05T11:03:13Z","qos_policy_id":null,"name":"dong","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T11:03:13Z","mtu":1450},{"updated_at":"2018-01-31T08:44:58Z","dns_domain":"","revision_number":9,"port_security_enabled":true,"id":"19576d0f-9e2f-43ce-ab2d-182f73998c5d","router:external":true,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"2b21740906894aaa908a8a443943aaf8","status":"ACTIVE","subnets":["8857b71d-52ae-4e0e-a72c-7ac1dcd78425"],"description":"","tags":[],"ipv6_address_scope":null,"is_default":false,"qos_policy_id":null,"name":"external","admin_state_up":true,"tenant_id":"2b21740906894aaa908a8a443943aaf8","created_at":"2018-01-18T11:19:44Z","mtu":1500},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"219b777e-76b5-4086-827f-67b8e6225d8a","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8f07dab4-0168-407a-8bb5-d2b02e7c7ff8"],"description":"","tags":[],"updated_at":"2018-01-31T10:16:11Z","qos_policy_id":null,"name":"test-fp","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-01-31T10:16:10Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"39aea290-5b63-4240-9c0f-cec5cd902d50","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8a464019-3fc4-450d-9e20-6b64c1f4a95d"],"description":"","tags":[],"updated_at":"2018-02-05T15:20:51Z","qos_policy_id":null,"name":"shift_on_stack","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T15:20:03Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"8025ff2d-19d6-4456-b765-d855a211b05d","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["8d165d58-fa04-46c5-8919-6fbcbe8ed4db"],"description":"","tags":[],"updated_at":"2018-02-05T10:15:04Z","qos_policy_id":null,"name":"bam","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T10:15:03Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"dd477cb7-ae97-41da-a8f7-55b25062b83d","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["bd5be583-2d72-4fa9-8b01-802f66f72caa"],"description":"","tags":[],"updated_at":"2018-01-18T11:51:08Z","qos_policy_id":null,"name":"internal","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-01-18T11:51:07Z","mtu":1450},{"ipv6_address_scope":null,"dns_domain":"","revision_number":4,"port_security_enabled":true,"id":"e510a7fc-042b-4cde-8213-c493d3c83ed5","router:external":false,"availability_zone_hints":[],"availability_zones":["x86_64"],"ipv4_address_scope":null,"shared":false,"project_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","status":"ACTIVE","subnets":["3c35c4da-47a1-44cd-9cd5-2f9abc1f484d"],"description":"","tags":[],"updated_at":"2018-02-05T10:22:47Z","qos_policy_id":null,"name":"joes-shift-on-stack","admin_state_up":true,"tenant_id":"fff63a91d7bd43c089d0c5bcdf8ebd48","created_at":"2018-02-05T10:22:25Z","mtu":1450}]}; line: 1, column: 2], status=0, status-code=CODE_UNKNOWN}
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.readEntity(HttpResponseImpl.java:125)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:69)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.networking.internal.NetworkServiceImpl.get(NetworkServiceImpl.java:65)
	at jenkins.plugins.openstack.compute.internal.Openstack.sanityCheck(Openstack.java:702)
	at jenkins.plugins.openstack.compute.JCloudsCloud$DescriptorImpl.doTestConnection(JCloudsCloud.java:421)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olivergondza** [comment]
Please report the issue against https://github.com/ContainX/openstack4j/ that provides the bindings. Thanks!

**Comment by Chekov2k** [comment]
Done: https://github.com/ContainX/openstack4j/issues/1148

**Comment by Chekov2k** [comment]
I can fix the problem by doing:
```
diff --git a/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java b/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java
index b6210ce..407e93d 100644
@@ -688,7 +688,7 @@ public class Openstack {
         // access them and JVM trusts their SSL cert.
         try {
             OSClient<?> client = clientProvider.get();
-            client.networking().network().get("");
+            client.networking().network().list().size();
             client.images().listMembers("");
             client.compute().listExtensions().size();
         } catch (Throwable ex) {
```
