### ISSUE TITLE
Regular exception when invalid credentials

### ISSUE THREAD

**Issue by Nancy-Robertson** [jenkinsci/openstack-cloud-plugin#219]
We noticed in our logs an exception coming up every 10 minutes as follows:
```
Sep 09, 2018 10:06:07 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (OpenStack slave cleanup thread/7874) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
AuthenticationException{message=Unauthorized, status=401}
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:36)
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
    at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:191)
    at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:74)
    at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:172)
    at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:129)
    at jenkins.plugins.openstack.compute.internal.Openstack.<init>(Openstack.java:127)
    at jenkins.plugins.openstack.compute.internal.Openstack.<init>(Openstack.java:108)
    at jenkins.plugins.openstack.compute.internal.Openstack$Factory.getOpenstack(Openstack.java:817)
    at jenkins.plugins.openstack.compute.internal.Openstack$FactoryEP$1.call(Openstack.java:774)
    at jenkins.plugins.openstack.compute.internal.Openstack$FactoryEP$1.call(Openstack.java:771)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
    at jenkins.plugins.openstack.compute.internal.Openstack$FactoryEP.get(Openstack.java:779)
    at jenkins.plugins.openstack.compute.JCloudsCloud.getOpenstack(JCloudsCloud.java:425)
    at jenkins.plugins.openstack.compute.JCloudsCleanupThread.destroyServersOutOfScope(JCloudsCleanupThread.java:145)
    at jenkins.plugins.openstack.compute.JCloudsCleanupThread.execute(JCloudsCleanupThread.java:63)
    at hudson.model.AsyncPeriodicWork$1.run(AsyncPeriodicWork.java:101)
    at java.lang.Thread.run(Thread.java:748)
```
Our jenkins is version 1.121.1 with the openstack cloud plugin 2.37.

After investigation, it turned out that the credential entry of one of the openstack cloud instances we had defined had an invalid password.

It would be helpful if the log reported the login failure instead of the exception.

**Comment by olivergondza** [comment]
The question is what to do here instead. Yes, we can log the exception ourselves instead of letting it to bubble up to the `hudson.model.AsyncPeriodicWork` but we would still likely want to log is at `SEVERE`. I guess we can hide the stacktrace in case we know it is `AuthenticationException`...

**Comment by olivergondza** [comment]
Additional diagnosis mentioning cloud and template would be good, though.

**Comment by olivergondza** [comment]
Also observed `ServerResponseException{message=Internal Server Error, status=500, status-code=INTERNAL_SERVER_ERROR}` to be logged here.

**Comment by olivergondza** [comment]
@Nancy-Robertson, thanks for the report. Improvement will go into the next release.
