### ISSUE TITLE
Provided Multiple possible networks found, use a Network ID to be more specific - Only one Network UID Provided

### ISSUE THREAD

**Issue by Gestahlt** [jenkinsci/openstack-cloud-plugin#233]
Hi,

I tried to set up a Jenkins Slave for builds using Openstack Cloud Plugin 2.42

When i try to create an instance from Jenkins i get this message:
```
ClientResponseException{message=Multiple possible networks found, use a Network ID to be more specific., status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:47)
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:69)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.boot(ServerServiceImpl.java:136)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.bootAndWaitActive(ServerServiceImpl.java:144)
	at jenkins.plugins.openstack.compute.internal.Openstack._bootAndWaitActive(Openstack.java:534)
	at jenkins.plugins.openstack.compute.internal.Openstack.bootAndWaitActive(Openstack.java:500)
Caused: jenkins.plugins.openstack.compute.internal.Openstack$ActionFailed: Multiple possible networks found, use a Network ID to be more specific.
	at jenkins.plugins.openstack.compute.internal.Openstack.bootAndWaitActive(Openstack.java:527)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provision(JCloudsSlaveTemplate.java:333)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provision(JCloudsSlaveTemplate.java:262)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:207)
	at jenkins.plugins.openstack.compute.JCloudsCloud.provisionSlave(JCloudsCloud.java:426)
	at jenkins.plugins.openstack.compute.JCloudsCloud.lambda$provisionAsynchronouslyNotToBlockTheRequestThread$0(JCloudsCloud.java:402)
	at hudson.security.ACL.impersonate(ACL.java:273)
	at jenkins.plugins.openstack.compute.JCloudsCloud.lambda$provisionAsynchronouslyNotToBlockTheRequestThread$1(JCloudsCloud.java:408)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


```
There is only one Network ID provided (and it is valid, works fine with Ansible, Curl, and so on).

Is this a bug in this version or is a workaround required?
Network ID is the normal OpenStack format, i tried enclosing it in ' and " just to be sure with no success.

We use Open Telekom Cloud as our cloud provider (Which is "kinda" OpenStack).
Here is a link to the API documentation if it helps:
https://docs.otc.t-systems.com/en-us/index.html?curpage=api

I hope we can resolve this somehow.
Thanks!

**Comment by olivergondza** [comment]
Check you jenkins log for 'Provisioning new openstack server'. It should contain the actual network name/id sent to openstack. Given the error from openstack, I suspect it might be empty.

**Comment by olivergondza** [comment]
Closing for the last of response.
