### ISSUE TITLE
HTTP 500 error with DreamCompute

### ISSUE THREAD

**Issue by ktdreyer** [jenkinsci/openstack-cloud-plugin#244]
When  I set up a connection to DreamCompute, I get an HTTP 500 error during `client.images().listMembers("")`

I'm using Endpoint URL `https://iad2.dream.io:5000/v2.0`, with an `Openstack Auth v2` credential.

```
ServerResponseException{message=Internal Server Error, status=500, status-code=INTERNAL_SERVER_ERROR}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:40)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:51)
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:69)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
	at org.openstack4j.openstack.image.internal.ImageServiceImpl.listMembers(ImageServiceImpl.java:189)
	at jenkins.plugins.openstack.compute.internal.Openstack.sanityCheck(Openstack.java:752)
	at jenkins.plugins.openstack.compute.JCloudsCloud$DescriptorImpl.doTestConnection(JCloudsCloud.java:510)
```

It looks like `Throwable.getMessage()` doesn't tell us quite enough about the error from the API. How can I get more information about what went wrong?

**Comment by olivergondza** [comment]
I am afraid this is tricky. I presume you can not wiretap the conversation so the 2 options I see are
- research the openstack4j ability to log communication details I have personally never got working or
- run the client in debugger and pause at `HttpEntityHandler.java:51`

**Comment by ktdreyer** [comment]
Any tips for running in a debugger? Do you use Eclipse?
