### ISSUE TITLE
Cloud statistics continually logs 'Completed' warning after Stack rename

### ISSUE THREAD

**Issue by eoghankennedy** [jenkinsci/openstack-cloud-plugin#246]
Hi,

Renaming a Stack while agents where active seems to have resulted in perpetual logging of warnings to Cloud Statistics.

```
java.lang.IllegalArgumentException: 'myXYZStack.com' is not an OpenStack cloud but null
	at jenkins.plugins.openstack.compute.JCloudsCloud.getByName(JCloudsCloud.java:104)
	at jenkins.plugins.openstack.compute.internal.DestroyMachine.dispose(DestroyMachine.java:50)
	at jenkins.plugins.openstack.compute.JCloudsSlave$RecordDisposal.dispose(JCloudsSlave.java:393)
	at org.jenkinsci.plugins.resourcedisposer.AsyncResourceDisposer$WorkItem.run(AsyncResourceDisposer.java:287)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Even by renaming the Stack back to the original entry dosnt make it happy.  Is there any way to stop this WARNING logging?  It is not affecting agent provisioning but it makes the Cloud Statistics hard to scroll through and I guess it will grow perpetually.

Any help appreciated!

**Comment by olivergondza** [comment]
Hmm, are those added as further and further attachments to the same provisioning attempt while still being tracked as disposables? That might easily grow on forever...

---

Reflecting the rename is tricky as cloud config update replaces set of clouds with another so telling simultanious addition and removal from rename is generally ambiguous. Though I guess there is a way for the `JCloudsSlave.RecordDisposal`'s to take less-frequently-mutated handle to a cloud instance (like url+project) and in case it gets gone, it will stop tracking the VMs.

**Comment by eoghankennedy** [comment]
Looks like further attachments

![agent_warnings](https://user-images.githubusercontent.com/28924369/53879989-b78e0f00-4007-11e9-82bf-9b0a86b92c66.png)

I guess the Cloud Stats eventually rotates so it should stop displaying?

**Comment by olivergondza** [comment]
@eoghankennedy, it will iff they are considered completed - which I am not sure of from the picture.

**Comment by olivergondza** [comment]
Which reminds me, you should be able to manually discard the problematic disposables so the plugin will no longer attempt to delete it. See: https://wiki.jenkins.io/display/JENKINS/Resource+Disposer+Plugin

**Comment by eoghankennedy** [comment]
I believe all the entries are 'Completed' so I'll reply if they don't fall off. 

The discard plugin looks useful.  I'll give that go.  Thanks for your help.

**Comment by olivergondza** [comment]
Cool, thanks!
