### ISSUE TITLE
An invalid name was provided

### ISSUE THREAD

**Issue by hanneskaeufler-bmw** [jenkinsci/openstack-cloud-plugin#259]
I am running into the error message below when manually provisioning a node and have been unable to pin it down.

* Error occurs with both 2.47, 2.46.1 of the plugin
* Jenkins 2.164.2
* Connected to a private cloud, the "Test connection" button succeeds.
* I have tested all kinds of names, node templates, settings etc.
* Suse OpenStack Cloud 7

Do you have any pointers on how to get to the bottom of this?

```
ClientResponseException{message=An invalid 'name' value was provided. The name must be: printable characters. Can not start or end with whitespace., status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:47)
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:69)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.boot(ServerServiceImpl.java:136)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.bootAndWaitActive(ServerServiceImpl.java:144)
	at jenkins.plugins.openstack.compute.internal.Openstack._bootAndWaitActive(Openstack.java:529)
	at jenkins.plugins.openstack.compute.internal.Openstack.bootAndWaitActive(Openstack.java:495)
Caused: jenkins.plugins.openstack.compute.internal.Openstack$ActionFailed: An invalid 'name' value was provided. The name must be: printable characters. Can not start or end with whitespace.
	at jenkins.plugins.openstack.compute.internal.Openstack.bootAndWaitActive(Openstack.java:522)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionServer(JCloudsSlaveTemplate.java:330)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:211)
	at jenkins.plugins.openstack.compute.JCloudsCloud.provisionSlaveExplicitly(JCloudsCloud.java:466)
	at jenkins.plugins.openstack.compute.JCloudsCloud.lambda$provisionAsynchronouslyNotToBlockTheRequestThread$2(JCloudsCloud.java:428)
	at jenkins.security.ImpersonatingScheduledExecutorService$2.call(ImpersonatingScheduledExecutorService.java:70)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olivergondza** [comment]
Check the Jenkins log for corresponding "INFO: Provisioning new openstack server " message to see, what exact name was openstack asked to use.

**Comment by hanneskaeufler-bmw** [comment]
```
Provisioning new openstack server linux-2 with options jenkins.plugins.openstack.compute.SlaveOptions@4263b1[bootSource=Image jenkins-linux-worker,hardwareId=5,networkId=16a58215-83b3-4f05-b309-1c0845084caf,userDataId=<null>,instanceCap=4,instancesMin=0,floatingIpPool=<null>,securityGroups=default, XXX, XXX, XXX, XXX,availabilityZone=AZ1,startTimeout=600000,keyPairName=XXX,numExecutors=4,jvmOptions=<null>,fsRoot=/var/jenkins,launcherFactory=LauncherFactory.SSH: credId:XXX, javaPath:null,retentionTime=30]
```

XXX is what I have redacted. So `linux-2` seems a perfectly fine name?

**Comment by olivergondza** [comment]
It does. Though the message have not mentioned it is a VM name it minds. Which brings me to the fact you are separating security groups with spaces, can you retest without spaces? So just `default,XXX,XXX,XXX,XXX`.

**Comment by hanneskaeufler-bmw** [comment]
You saved my week. ❤️ Spaces after the comma in the list are the problem.
