### ISSUE TITLE
Windows slave getting terminated after provision

### ISSUE THREAD

**Issue by gowthamsubbu** [jenkinsci/openstack-cloud-plugin#296]
We are using OpenStack cloud plugin to provision Windows worker in P9 with Jenkins master in AWS. Interestingly, we are seeing nodes getting provisioned and also getting terminated (by the plugin) before the startup timeout set (600000ms ~ 10 mins) and plugin still trying to connect with the terminated the node agent.

Provisioning -> provisioned -> Creating a new computer -> Deleting slave -> Deleted slave -> Failed to connect with worker agent (when startup timeout is met)

Basically, our understanding is that plugin terminates the node (reason is unknown) and still tries to connect with the node agent until the startup timeout is met without knowing its state.

```
2020-04-23 15:08:14.272+0000 [id=35]    INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server af-jenkins-win-1 with options jenkins.plugins.openstack.compute.SlaveOptions@37269d8e[bootSource=Image afj_slave_win_2.14.0,hardwareId=10004001,networkId=02733df5-88ef-4a98-886e-11576372f6c4,userDataId=af-jenkins-userdata-win,instanceCap=4,instancesMin=0,floatingIpPool=<null>,securityGroups=default,availabilityZone=HA-Win,startTimeout=600000,keyPairName=jenkins,numExecutors=4,jvmOptions=<null>,fsRoot=c:/jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false]
2020-04-23 15:08:14.969+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:15.547+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:17.538+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:18.992+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:20.503+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:22.033+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:23.561+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:25.235+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:26.999+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:28.736+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:30.394+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:31.346+0000 [id=329]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #61 failed: java.io.EOFException
2020-04-23 15:08:32.781+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:34.919+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:36.575+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:08:36.939+0000 [id=35]    INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioned: NovaServer{id=9f3fa0f6-4bf4-4871-bfba-0ca7efedaf35, name=af-jenkins-win-1, image={id=e255b22b-b94b-4315-944b-0af3de03aa4d, links=[{href=https://xxxxxx.platform9.net/nova/xxxxxx/images/e255b22b-b94b-4315-944b-0af3de03aa4d, rel=bookmark}]}, flavor=NovaFlavor{id=10004001, ephemeral=0, swap=0, rxtx_factor=1.0, links=[GenericLink{href=https://xxxxxxx.platform9.net/nova/xxxxxxxxx/flavors/10004001, rel=bookmark}],
}, status=ACTIVE, diskconfig=MANUAL, userId=xxxxxx, created=Thu Apr 23 11:08:17 EDT 2020, updated=Thu Apr 23 11:08:35 EDT 2020, launched at=Thu Apr 23 11:08:34 EDT 2020, tenantId=xxxxxxx, hostId=xxxxxx, addresses=NovaAddresses{addresses={SDLC=[NovaAddress{address=10.83.83.17, type=fixed, version=4, macaddr=fa:16:3e:04:6d:08,
}]},
}, powerstate=1, vmState=active, metadata={jenkins-boot-image-id=e255b22b-b94b-4315-944b-0af3de03aa4d, jenkins-cloud-name=sdlc, jenkins-template-name=af-jenkins-win, jenkins-instance=https://jenkins-xxxxxxx.com/, jenkins-scope=node:af-jenkins-win-1:-109976168, jenkins-boot-source=Image afj_slave_win_2.14.0}}
2020-04-23 15:08:36.940+0000 [id=35]    INFO    j.p.o.compute.JCloudsSlave#createComputer: Creating a new computer for af-jenkins-win-1
2020-04-23 15:08:39.819+0000 [id=347]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #62 failed: java.io.EOFException
2020-04-23 15:09:01.347+0000 [id=356]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #63 failed: java.io.EOFException
2020-04-23 15:09:09.820+0000 [id=357]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #64 failed: java.io.EOFException
2020-04-23 15:09:31.346+0000 [id=358]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #65 failed: java.io.EOFException
2020-04-23 15:09:39.820+0000 [id=362]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #66 failed: java.io.EOFException
2020-04-23 15:10:01.347+0000 [id=369]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #67 failed: java.io.EOFException
2020-04-23 15:10:02.721+0000 [id=16]    INFO    c.s.o.i.Platform$JdkWithJettyBootPlatform#getSelectedProtocol: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:03.716+0000 [id=16]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:04.702+0000 [id=16]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:05.351+0000 [id=360]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:06.097+0000 [id=360]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:06.270+0000 [id=361]   INFO    j.p.o.compute.JCloudsComputer#deleteSlave: Deleting slave af-jenkins-win-1 after executing 0 builds
2020-04-23 15:10:06.300+0000 [id=361]   INFO    j.p.o.compute.JCloudsComputer#deleteSlave: Deleted slave af-jenkins-win-1
2020-04-23 15:10:06.571+0000 [id=377]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:07.334+0000 [id=377]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:08.075+0000 [id=377]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:08.767+0000 [id=377]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:10:09.819+0000 [id=379]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #68 failed: java.io.EOFException
2020-04-23 15:10:31.347+0000 [id=380]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #69 failed: java.io.EOFException
2020-04-23 15:10:39.819+0000 [id=382]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #70 failed: java.io.EOFException
2020-04-23 15:11:01.346+0000 [id=389]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #71 failed: java.io.EOFException
2020-04-23 15:11:09.819+0000 [id=390]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #72 failed: java.io.EOFException
2020-04-23 15:11:31.347+0000 [id=391]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #73 failed: java.io.EOFException
2020-04-23 15:11:39.820+0000 [id=392]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #74 failed: java.io.EOFException
2020-04-23 15:12:01.347+0000 [id=399]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #75 failed: java.io.EOFException
2020-04-23 15:12:09.820+0000 [id=400]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #76 failed: java.io.EOFException
2020-04-23 15:12:31.347+0000 [id=405]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #77 failed: java.io.EOFException
2020-04-23 15:12:39.820+0000 [id=407]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #78 failed: java.io.EOFException
2020-04-23 15:13:01.347+0000 [id=414]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #79 failed: java.io.EOFException
2020-04-23 15:13:09.819+0000 [id=415]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #80 failed: java.io.EOFException
2020-04-23 15:13:26.192+0000 [id=416]   OFF     hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started OpenStack slave cleanup
2020-04-23 15:13:26.570+0000 [id=416]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:13:27.181+0000 [id=416]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:13:28.338+0000 [id=416]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:13:28.686+0000 [id=416]   OFF     hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished OpenStack slave cleanup. 2,494 ms
2020-04-23 15:13:31.347+0000 [id=421]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #81 failed: java.io.EOFException
2020-04-23 15:13:39.820+0000 [id=422]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #82 failed: java.io.EOFException
2020-04-23 15:14:01.347+0000 [id=429]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #83 failed: java.io.EOFException
2020-04-23 15:14:09.820+0000 [id=430]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #84 failed: java.io.EOFException
2020-04-23 15:14:31.347+0000 [id=432]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #85 failed: java.io.EOFException
2020-04-23 15:14:39.820+0000 [id=434]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #86 failed: java.io.EOFException
2020-04-23 15:15:01.350+0000 [id=441]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #87 failed: java.io.EOFException
2020-04-23 15:15:02.131+0000 [id=13]    INFO    c.s.o.i.Platform$JdkWithJettyBootPlatform#getSelectedProtocol: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
2020-04-23 15:15:09.820+0000 [id=442]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #88 failed: java.io.EOFException
2020-04-23 15:15:31.396+0000 [id=444]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #89 failed: java.io.EOFException
2020-04-23 15:15:39.820+0000 [id=445]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #90 failed: java.io.EOFException
2020-04-23 15:16:01.347+0000 [id=452]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #91 failed: java.io.EOFException
2020-04-23 15:16:09.820+0000 [id=453]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #92 failed: java.io.EOFException
2020-04-23 15:16:31.347+0000 [id=455]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #93 failed: java.io.EOFException
2020-04-23 15:16:39.820+0000 [id=457]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #94 failed: java.io.EOFException
2020-04-23 15:17:01.346+0000 [id=464]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #95 failed: java.io.EOFException
2020-04-23 15:17:09.820+0000 [id=465]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #96 failed: java.io.EOFException
2020-04-23 15:17:14.797+0000 [id=466]   INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started EC2 alive slaves monitor
2020-04-23 15:17:14.798+0000 [id=466]   INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished EC2 alive slaves monitor. 1 ms
2020-04-23 15:17:31.347+0000 [id=468]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #97 failed: java.io.EOFException
2020-04-23 15:17:39.819+0000 [id=469]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #98 failed: java.io.EOFException
2020-04-23 15:18:01.347+0000 [id=476]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #99 failed: java.io.EOFException
2020-04-23 15:18:09.819+0000 [id=477]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #100 failed: java.io.EOFException
2020-04-23 15:18:31.347+0000 [id=479]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #101 failed: java.io.EOFException
2020-04-23 15:18:37.267+0000 [id=35]    INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-04-23 15:18:37.528+0000 [id=35]    WARNING j.p.o.c.JCloudsSlaveTemplate#provisionSlave: Failed to connect agent af-jenkins-win-1 within timeout (600000 ms): JNLP connection was not established yet
Server does no longer exist: 9f3fa0f6-4bf4-4871-bfba-0ca7efedaf35
2020-04-23 15:18:37.552+0000 [id=35]    WARNING j.p.o.compute.JCloudsCloud#lambda$provisionAsynchronouslyNotToBlockTheRequestThread$2: Provisioning failed
jenkins.plugins.openstack.compute.JCloudsCloud$ProvisioningFailedException: Failed to connect agent af-jenkins-win-1 within timeout (600000 ms): JNLP connection was not established yet
Server does no longer exist: 9f3fa0f6-4bf4-4871-bfba-0ca7efedaf35
        at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:239)
        at jenkins.plugins.openstack.compute.JCloudsCloud.provisionSlaveExplicitly(JCloudsCloud.java:467)
        at jenkins.plugins.openstack.compute.JCloudsCloud.lambda$provisionAsynchronouslyNotToBlockTheRequestThread$2(JCloudsCloud.java:429)
        at jenkins.security.ImpersonatingScheduledExecutorService$2.call(ImpersonatingScheduledExecutorService.java:70)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-04-23 15:18:37.553+0000 [id=35]    WARNING j.u.ErrorLoggingScheduledThreadPoolExecutor#afterExecute: failure in task not wrapped in SafeTimerTask
jenkins.plugins.openstack.compute.JCloudsCloud$ProvisioningFailedException: Failed to connect agent af-jenkins-win-1 within timeout (600000 ms): JNLP connection was not established yet
Server does no longer exist: 9f3fa0f6-4bf4-4871-bfba-0ca7efedaf35
        at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:239)
        at jenkins.plugins.openstack.compute.JCloudsCloud.provisionSlaveExplicitly(JCloudsCloud.java:467)
        at jenkins.plugins.openstack.compute.JCloudsCloud.lambda$provisionAsynchronouslyNotToBlockTheRequestThread$2(JCloudsCloud.java:429)
        at jenkins.security.ImpersonatingScheduledExecutorService$2.call(ImpersonatingScheduledExecutorService.java:70)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
 
This behavior is not constant and definitely intermittent. If we spin up 10 windows worker 4-5 will fail with similar issue. Worker deletion is not happening as a part of Slave cleanup, since we couldn't find any log trace to warrant.

Tested with 2.51 and 2.52 and the behavior is same.

**Comment by gowthamsubbu** [comment]
Issue turned out to be unrelated to plugin. Closing.
