### ISSUE TITLE
Provisioning failed :  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Tas-sos** [jenkinsci/openstack-cloud-plugin#348]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.346.2
OS: Linux - 4.18.0-372.9.1.el8.x86_64
---
Parameterized-Remote-Trigger:3.1.6.3
ace-editor:1.1
analysis-model-api:10.13.0
ansicolor:1.0.2
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
audit-trail:3.11
authentication-tokens:1.4
badge:1.9.1
blueocean:1.25.5
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-config:1.25.5
blueocean-core-js:1.25.5
blueocean-dashboard:1.25.5
blueocean-display-url:2.4.1
blueocean-events:1.25.5
blueocean-git-pipeline:1.25.5
blueocean-github-pipeline:1.25.5
blueocean-i18n:1.25.5
blueocean-jwt:1.25.5
blueocean-personalization:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-editor:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
bugzilla:1.5
build-timeout:1.21
bulk-builder:1.5
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloud-stats:0.27
cloudbees-bitbucket-branch-source:784.v7fcdc7c670f6
cloudbees-disk-usage-simple:170.va_fd5b_4ee6858
cloudbees-folder:6.736.v5f554b_b_a_52b_3
command-launcher:84.v4a_97f2027398
commons-lang3-api:3.12.0.0
commons-text-api:1.9-9.v39a_53e2e0343
compact-columns:1.148.v649c8db_2a_91e
conditional-buildstep:1.4.2
config-file-provider:3.11.1
configuration-as-code:1512.vb_79d418d5fc8
configurationslicing:430.v966357576543
copr:0.6.1
copyartifact:1.46.4
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
cron_column:1.4
dashboard-view:2.447.vda_124dd35f11
data-tables-api:1.12.1-2
discard-old-build:1.05
display-url-api:2.3.6
docker-build-publish:1.3.3
docker-commons:1.19
docker-workflow:1.29
durable-task:496.va67c6f9eefa7
echarts-api:5.3.3-1
email-ext:2.91
embeddable-build-status:237.v37e2c03964c9
envinject:2.866.v5c0403e3d4df
envinject-api:1.199.v3ce31253ed13
extended-read-permission:3.2
external-monitor-job:192.ve979ca_8b_3ccd
extra-columns:1.25
favorite:2.4.1
flexible-publish:0.16.1
font-awesome-api:6.1.1-1
forensics-api:1.15.1
generic-webhook-trigger:1.84
gerrit-trigger:2.36.0
ghprb:1.42.2
git:4.11.4
git-client:3.11.1
git-server:1.11
github:1.34.5
github-api:1.303-400.v35c2d8258028
github-branch-source:1677.v731f745ea_0cf
global-build-stats:244.v27c8a_2e50a_34
google-login:1.6
google-oauth-plugin:1.0.6
greenballs:1.15.1
groovy:442.v817e6d937d6c
groovy-postbuild:2.5
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
jackson2-api:2.13.3-285.vc03c0256d517
jakarta-activation-api:2.0.0-3
jakarta-mail-api:2.0.0-6
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jjwt-api:0.11.5-77.v646c772fddb_0
jms-messaging:1.1.27
jobConfigHistory:1163.ve82c7c6e60a_3
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
kerberos-sso:1.9
kubernetes:3670.v6ca_059233222
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
ldap:2.11
linenumbers:1.3
lockable-resources:2.16
mailer:435.v79ef3972b_5c7
mapdb-api:1.0.9.0
mask-passwords:3.3
matrix-auth:3.1.5
matrix-project:772.v494f19991984
matrix-reloaded:1.1.3
maven-plugin:3.19
mercurial:2.16.2
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.8.0-36.v8e25ce90d4b_1
mina-sshd-api-core:2.8.0-36.v8e25ce90d4b_1
momentjs:1.1.1
monitoring:1.91.0
multi-slave-config-plugin:1.2.0
multiple-scms:0.8
naginator:1.18.1
nested-view:1.26
nodelabelparameter:1.11.0
nodenamecolumn:1.2
notification:1.15
oauth-credentials:0.5
okhttp-api:4.9.3-105.vb96869f8ac3a
openshift-client:1.0.37
openshift-login:1.0.27
openshift-pipeline:1.0.57
openshift-sync:1.0.53
openstack-cloud:2.63
pam-auth:1.8
parameterized-trigger:2.45
pipeline-build-step:2.18
pipeline-github-lib:38.v445716ea_edda_
pipeline-githubnotify-step:49.vf37bf92d2bc8
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:598.vcd66b_a_336510
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2114.v2654ca_721309
pipeline-model-definition:2.2114.v2654ca_721309
pipeline-model-extensions:2.2114.v2654ca_721309
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2114.v2654ca_721309
pipeline-stage-view:2.24
pipeline-utility-steps:2.13.0
plain-credentials:1.8
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
postbuild-task:1.9
preSCMbuildstep:0.3
prism-api:1.28.0-2
progress-bar-column-plugin:1.0
prometheus:2.0.11
promoted-builds:878.v12d3f7937690
publish-over:0.22
publish-over-ssh:1.24
pubsub-light:1.16
purge-build-queue-plugin:48.v39c52a_26a_264
rebuild:1.34
resource-disposer:0.19
role-strategy:546.ve16648865996
run-condition:1.5
scm-api:616.ve67136f6c77d
script-security:1175.v4b_d517d6db_f0
simple-theme-plugin:103.va_161d09c38c7
snakeyaml-api:1.30.2-76.vc104f7ce9870
sse-gateway:1.25
ssh:2.6.1
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:295.vced876c18eb_4
ssh-slaves:1.834.v622da_57f702c
sshd:3.242.va_db_9da_b_26a_c3
structs:324.va_f5d6774f3a_d
swarm:3.34
test-results-analyzer:0.3.5
throttle-concurrents:2.8
timestamper:1.18
token-macro:308.v4f2b_ed62b_b_16
trilead-api:1.67.vc3938a_35172f
variant:59.vf075fe829ccb
view-job-filters:2.3
warnings-ng:9.14.0
whitesource:21.1.2
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1188.v0016b_4f29881
workflow-basic-steps:986.v6b_9c830a_6b_37
workflow-cps:2759.v87459c4eea_ca_
workflow-cps-global-lib:588.v576c103a_ff86
workflow-durable-task-step:1199.v02b_9244f8064
workflow-job:1207.ve6191ff089f8
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:833.va_1c71061486b_
ws-cleanup:0.42
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

* Base OS : `Red Hat Enterprise Linux 8.6 (Ootpa)`
* Jenkins master : `2.346.2`
* I am trying to create a CentOS **7** instance via **OpenStack**.

### Reproduction steps

I just want to configure **Configure Clouds** ( `https://example-jenkins.com/configureClouds/` ) so that Jenkins runs all jobs in a instances it will create in our OpenStack.
With exactly the same configuration, I am able to create a new instance directly from OpenStack dashboard. I do not know why this Jenkins plugin fails.

### Expected Results

Successfully creating the new instance and running the job on it.

### Actual Results

```
Jul 28, 2022 4:56:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 4:56:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms

Jul 28, 2022 4:58:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 4:58:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 1 ms

Jul 28, 2022 4:58:56 AM OFF hudson.model.AsyncPeriodicWork lambda$doRun$1
Started OpenStack slave cleanup

Jul 28, 2022 4:58:57 AM FINE jenkins.plugins.openstack.compute.internal.Openstack
Openstack client created for "OpenstackCredentialv3{username='jenkins-automation', userDomain='example.com', projectName='devops', projectDomain='example.com'}", "regionOne".

Jul 28, 2022 4:58:58 AM OFF hudson.model.AsyncPeriodicWork lambda$doRun$1
Finished OpenStack slave cleanup. 1,836 ms

Jul 28, 2022 4:59:23 AM FINE jenkins.plugins.openstack.compute.internal.Openstack
Openstack client created for "OpenstackCredentialv3{username='jenkins-automation', userDomain='example.com', projectName='devops', projectDomain='example.com'}", "null".

Jul 28, 2022 4:59:23 AM FINE jenkins.plugins.openstack.compute.internal.Openstack
Openstack client created for "OpenstackCredentialv3{username='jenkins-automation', userDomain='example.com', projectName='devops', projectDomain='example.com'}", "null".

Jul 28, 2022 5:00:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 5:00:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms

Jul 28, 2022 5:02:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 5:02:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms

Jul 28, 2022 5:03:36 AM INFO jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
Provisioning new openstack server el7-staging-jenkins-worker-0 with options jenkins.plugins.openstack.compute.SlaveOptions@42812d25[bootSource=Image centos7-worker-image-8e8e0c69,hardwareId=ab34d89f-a105-4c93-a7d9-185e327fa6d0,networkId=provider_net_cci_8,userDataId=<null>,instanceCap=2,instancesMin=0,floatingIpPool=<null>,securityGroups=default,test,availabilityZone=nova,startTimeout=120000,keyPairName=jenkins-slave,numExecutors=1,jvmOptions=<null>,fsRoot=/root,launcherFactory=<null>,nodeProperties=<null>,retentionTime=30,configDrive=false]

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting boot options to Image centos7-worker-image-8e8e0c69

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting hardware Id to ab34d89f-a105-4c93-a7d9-185e327fa6d0

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting networks to [60cacaff-86a6-4f88-82a4-ed3023724df1]

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting security groups to default,test

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting keyPairName to jenkins-slave

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting availabilityZone to nova

Jul 28, 2022 5:03:36 AM FINE jenkins.plugins.openstack.compute.internal.Openstack
Booting machine

Jul 28, 2022 5:04:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 5:04:03 AM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms


Jul 28, 2022 5:04:06 AM FINE jenkins.plugins.openstack.compute.internal.Openstack
Machine started: el7-staging-jenkins-worker-0


Jul 28, 2022 5:04:06 AM INFO jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
Provisioned: NovaServer{id=d56b0390-a0dc-4343-926d-fe4c29cad9a7, name=el7-staging-jenkins-worker-0, image={id=153bfeab-b950-4ba0-b35c-6a56c1f3d277, links=[{rel=bookmark, href=https://openstack.example.com:13774/images/153bfeab-b950-4ba0-b35c-6a56c1f3d277}]}, flavor=NovaFlavor{id=ab34d89f-a105-4c93-a7d9-185e327fa6d0, ephemeral=0, swap=0, rxtx_factor=1.0, links=[GenericLink{href=https://openstack.example.com:13774/flavors/ab34d89f-a105-4c93-a7d9-185e327fa6d0, rel=bookmark}], 
}, status=ACTIVE, diskconfig=MANUAL, userId=468f2f88fbea0e34fb56291a6ac763ad5dd04cfb2c91dd94b79973029725a78d, created=Thu Jul 28 05:03:37 EDT 2022, updated=Thu Jul 28 05:04:05 EDT 2022, launched at=Thu Jul 28 05:04:05 EDT 2022, tenantId=70cc11b6cbd94a258690eb067410536e, hostId=771f12815854e3592d08026a5ef395e8e6dc26cb740a84429f9ac376, addresses=NovaAddresses{addresses={provider_net_cci_8=[NovaAddress{address=10.0.102.167, type=fixed, version=4, macaddr=fa:16:3e:a9:ba:7a, 
}]}, 
}, powerstate=1, vmState=active, metadata={jenkins-template-name=el7-staging-jenkins-worker, jenkins-identity=e193fe6dbbd50151167531dd99ff4c0c5608b4e9, jenkins-scope=node:el7-staging-jenkins-worker-0:1278986973, jenkins-instance=https://jenkins.example.com/, jenkins-cloud-name=openstack, jenkins-boot-source=Image centos7-worker-image-8e8e0c69, jenkins-boot-image-id=153bfeab-b950-4ba0-b35c-6a56c1f3d277}}


Jul 28, 2022 5:04:06 AM INFO jenkins.plugins.openstack.compute.JCloudsSlave createComputer
Creating a new computer for el7-staging-jenkins-worker-0


Jul 28, 2022 5:04:06 AM WARNING jenkins.plugins.openstack.compute.JCloudsCloud lambda$provisionAsynchronouslyNotToBlockTheRequestThread$2
Provisioning failed
java.lang.NullPointerException
	at jenkins.plugins.openstack.compute.JCloudsCloud.slaveIsWaitingFor(JCloudsCloud.java:341)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:225)
Caused: jenkins.plugins.openstack.compute.JCloudsCloud$ProvisioningFailedException
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:254)
	at jenkins.plugins.openstack.compute.JCloudsCloud.provisionSlaveExplicitly(JCloudsCloud.java:467)
	at jenkins.plugins.openstack.compute.JCloudsCloud.lambda$provisionAsynchronouslyNotToBlockTheRequestThread$2(JCloudsCloud.java:429)
	at jenkins.security.ImpersonatingScheduledExecutorService$2.call(ImpersonatingScheduledExecutorService.java:79)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

**Comment by Tas-sos** [comment]
Because now we are using **Java 11** in Jenkins master, I create a new image based on the previous one **CentOS 7** but now with **Java 11** by default.

But the problem still exists :
```logs
Jul 28, 2022 12:41:17 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 12:41:17 PM INFO jenkins.plugins.openstack.compute.JCloudsPreCreationThread execute
Pre-creating 1 instance(s) for template el7-staging-downstream-jenkins-worker in cloud example-openstack

Jul 28, 2022 12:41:17 PM INFO jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
Provisioning new openstack server el7-staging-downstream-jenkins-worker-43 with options jenkins.plugins.openstack.compute.SlaveOptions@571298cf[bootSource=Image centos7-java11-jenkins-worker,hardwareId=2695501c-9029-4c05-aae2-34b1b17e8810,networkId=provider_net_cci_8,userDataId=<null>,instanceCap=2,instancesMin=1,floatingIpPool=<null>,securityGroups=default,test,availabilityZone=nova,startTimeout=240000,keyPairName=example-jenkins-slave,numExecutors=1,jvmOptions=<null>,fsRoot=/root,launcherFactory=<null>,nodeProperties=<null>,retentionTime=30,configDrive=false]

Jul 28, 2022 12:41:17 PM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting boot options to Image centos7-java11-jenkins-worker

Jul 28, 2022 12:41:18 PM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting hardware Id to 2695501c-9029-4c05-aae2-34b1b17e8810

Jul 28, 2022 12:41:18 PM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting networks to [60cacaff-86a6-4f88-82a4-ed3023724df1]

Jul 28, 2022 12:41:18 PM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting security groups to default,test

Jul 28, 2022 12:41:18 PM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting keyPairName to example-jenkins-slave

Jul 28, 2022 12:41:18 PM FINE jenkins.plugins.openstack.compute.JCloudsSlaveTemplate
Setting availabilityZone to nova

Jul 28, 2022 12:41:18 PM FINE jenkins.plugins.openstack.compute.internal.Openstack
Booting machine

Jul 28, 2022 12:42:26 PM FINE jenkins.plugins.openstack.compute.internal.Openstack
Machine started: el7-staging-downstream-jenkins-worker-43

Jul 28, 2022 12:42:26 PM INFO jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
Provisioned: NovaServer{id=bac97aa3-1bf5-42b9-8822-1d78f9df7abb, name=el7-staging-downstream-jenkins-worker-43, image={id=5cbd02af-ad9d-490c-ae40-e99796c6a354, links=[{rel=bookmark, href=https://openstack-example.com:13774/images/5cbd02af-ad9d-490c-ae40-e99796c6a354}]}, flavor=NovaFlavor{id=2695501c-9029-4c05-aae2-34b1b17e8810, ephemeral=0, swap=0, rxtx_factor=1.0, links=[GenericLink{href=https://openstack-example.com:13774/flavors/2695501c-9029-4c05-aae2-34b1b17e8810, rel=bookmark}], 
}, status=ACTIVE, diskconfig=MANUAL, userId=468f2f88fbea0e34fb56291a6ac763ad5dd04cfb2c91dd94b79973029725a78d, created=Thu Jul 28 12:41:19 EDT 2022, updated=Thu Jul 28 12:42:25 EDT 2022, launched at=Thu Jul 28 12:42:25 EDT 2022, tenantId=70cc11b6cbd94a258690eb067410536e, hostId=6ec55763dd3cd709e067b7e572998ec2a4efc38c662ab206353ff732, addresses=NovaAddresses{addresses={provider_net_cci_8=[NovaAddress{address=10.0.103.13, type=fixed, version=4, macaddr=fa:16:3e:f9:e7:5b, 
}]}, 
}, powerstate=1, vmState=active, metadata={jenkins-template-name=el7-staging-downstream-jenkins-worker, jenkins-identity=e193fe6dbbd50151167531dd99ff4c0c5608b4e9, jenkins-scope=node:el7-staging-downstream-jenkins-worker-43:452015938, jenkins-instance=https://jenkins-example.com/, jenkins-cloud-name=example-openstack, jenkins-boot-source=Image centos7-java11-jenkins-worker, jenkins-boot-image-id=5cbd02af-ad9d-490c-ae40-e99796c6a354}}

Jul 28, 2022 12:42:26 PM INFO jenkins.plugins.openstack.compute.JCloudsSlave createComputer
Creating a new computer for el7-staging-downstream-jenkins-worker-43

Jul 28, 2022 12:42:26 PM SEVERE jenkins.plugins.openstack.compute.JCloudsPreCreationThread execute
Failed to pre-create instance from template el7-staging-downstream-jenkins--worker
java.lang.NullPointerException
	at jenkins.plugins.openstack.compute.JCloudsCloud.slaveIsWaitingFor(JCloudsCloud.java:341)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:225)
Caused: jenkins.plugins.openstack.compute.JCloudsCloud$ProvisioningFailedException
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:254)
	at jenkins.plugins.openstack.compute.JCloudsCloud.provisionSlaveExplicitly(JCloudsCloud.java:467)
	at jenkins.plugins.openstack.compute.JCloudsPreCreationThread.execute(JCloudsPreCreationThread.java:86)
	at hudson.model.AsyncPeriodicWork.lambda$doRun$1(AsyncPeriodicWork.java:102)
	at java.base/java.lang.Thread.run(Thread.java:829)

Jul 28, 2022 12:42:26 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 69,743 ms

Jul 28, 2022 12:42:27 PM FINE jenkins.plugins.openstack.compute.internal.Openstack
Openstack client created for "OpenstackCredentialv3{username='example-jenkins-automation', userDomain='example.com', projectName='devops', projectDomain='example.com'}", "regionOne".

Jul 28, 2022 12:42:35 PM FINEST jenkins.plugins.openstack.compute.JCloudsRetentionStrategy
Checking

Jul 28, 2022 12:43:17 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation

Jul 28, 2022 12:43:17 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms
```

I don't know what else I can do or what the problem is.
Can I somehow get more logs?

**Comment by Tas-sos** [comment]
The log files does not help us about where the error is. It doesn't tell us if a field is missing or where the problem might be.
In the end after many different attempts and after consulting the configurations of others I found what was needed. It was just the filled "**Connection Type**".
![Screenshot 2022-08-01 at 12-52-34 Configure Clouds  Jenkins](https://user-images.githubusercontent.com/9154286/183909652-44001490-c8d6-45df-bc72-f306bb95b86e.png)

After that everything works perfectly!
